name: Node.js CI

# CI should be runned on master branch and on PR targeting master
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs: # Jobs are a group of steps
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # Actions are "packages" for GHA
      - uses: actions/setup-node@v2
        with: # Actions can have parameters
          node-version: 14.x
      - run: yarn install
      - run: tar -zcf node_modules.tar.gz ./node_modules
      - uses: actions/upload-artifact@v2
        with:
          name: project-dependencies
          path: node_modules.tar.gz
          retention-days: 1

  test:
    runs-on: ubuntu-latest

    needs: install

    strategy:
      matrix:
        include:
          - variable: bonjour
          - variable: coucou
          - variable: salut

    steps:
      - uses: actions/checkout@v2 # Actions are "packages" for GHA
      - uses: actions/setup-node@v2
        with: # Actions can have parameters
          node-version: 14.x
      - uses: actions/download-artifact@v2
        with:
          name: project-dependencies
      - run: tar -zxf node_modules.tar.gz
      - run: TEST=${{matrix.variable}} yarn test

  build:
    runs-on: ubuntu-latest

    needs: install

    steps:
      - uses: actions/checkout@v2 # Actions are "packages" for GHA
      - uses: actions/setup-node@v2
        with: # Actions can have parameters
          node-version: 14.x
      - uses: actions/download-artifact@v2
        with:
          name: project-dependencies
      - run: tar -zxf node_modules.tar.gz
      - run: yarn build
      - run: tar -zcf dist.tar.gz ./dist
      - uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: dist.tar.gz
          retention-days: 1

  e2e:
    runs-on: ubuntu-latest

    needs: install

    needs: build

    steps:
      - uses: actions/checkout@v2 # Actions are "packages" for GHA
      - uses: actions/setup-node@v2
        with: # Actions can have parameters
          node-version: 14.x
      - uses: actions/download-artifact@v2
        with:
          name: app-build
      - run: tar -zxf dist.tar.gz
      - run: yarn e2e
